### ISSUE TITLE
[FIX] 코스 둘러보기 & 코스 상세 1차 QA 반영

### ISSUE THREAD

**Issue by kms0233** [TeamDATEROAD/DATEROAD-iOS#124]
## 🛠 Issue

1차 QA 반영 
## 📝 To-do

- [ ] 좋아요 실시간 반영
- [ ] 이미지 밀림 오류
- [ ] 코스 둘러보기 시간 값 바인딩 에러
