### ISSUE TITLE
[REFACTOR] 코스 둘러보기 리팩토링

### ISSUE THREAD

**Issue by kms0233** [TeamDATEROAD/DATEROAD-iOS#143]
## 🛠 Issue

코스 둘러보기 MVVM 적용시켜서 제대로 리팩토링 진행할 예정입니다!

## 📝 To-do

- [x] 코스 필터링 뷰 리팩토링
- [x] 코스 리스트 컬렉션 뷰 리팩토링
- [x] 코스 필터링 바텀 시트 리팩토링
