### ISSUE TITLE
[REFACTOR] 내가 열람한 코스 리팩토링

### ISSUE THREAD

**Issue by cirtuare** [TeamDATEROAD/DATEROAD-iOS#149]
## 🛠 Issue
내가 열람한 코스 화면을 리팩토링합니다.

## 📝 To-do

- [ ] 내가 열람한 코스 리팩토링
- [ ] 상단 문구 분기처리 에러 해결
- [ ] viewDidAppear로 데이터 동기화하는 방식 변경 시도
