### ISSUE TITLE
[REFACTOR] 코스 상세 버그 수정 및 리팩토링

### ISSUE THREAD

**Issue by kms0233** [TeamDATEROAD/DATEROAD-iOS#151]
## 🛠 Issue

코스 상세보기 네트워크 통신 및 분기처리에 대한 코드 리팩토링 할 예정입니다

## 📝 To-do

- [x]  kingfisher extension 추가해서 코드 수정
- [x]  바텀 네비바 가림뷰 보다 밑에 계층에 있도록 수정
- [x]  타임라인 번호 인덱스 수정
- [ ]  이미 열람한 코스 가림뷰 안보이도록 시점 다시 수정해보기
- [ ]  비용/시간/위치 아이콘 위치 디자인한테 다시 물어보고 수정하기
