### ISSUE TITLE
[FIX] '코스 등록', '일정 등록' 변경 사항에 따른 코드 수정

### ISSUE THREAD

**Issue by ParkSY0919** [TeamDATEROAD/DATEROAD-iOS#156]
## 🛠 Issue
- 서버와 디자인 변경 사항에 따른 코드 수정

## 📝 To-do

- [x] `코스 등록하기` 파트 코드 수정
- [x] `일정 등록하기` 파트 코드 수정
- [x] 지역 필터링 디자인 변경 적용
