### ISSUE TITLE
[FEAT] 코스 상세 변경된 GUI 적용 및 플로우 수정

### ISSUE THREAD

**Issue by kms0233** [TeamDATEROAD/DATEROAD-iOS#160]
## 🛠 Issue

코스 상세에서 시작 시간 추가 되어서 반영할 예정이고
코스 삭제 시 팝업창 뜨도록 플로우 수정되어서 추가할 예정입니다!

## 📝 To-do

- [x] 시작 시간 추가하기
- [x] 삭제 시 팝업창 뜨도록 수정하기
- [x] 구글폼 URL 적용시키기
- [x] 기타 QA 반영하기
