### ISSUE TITLE
[REFACTOR] 메인뷰 리팩토링

### ISSUE THREAD

**Issue by seuriseuljjeok** [TeamDATEROAD/DATEROAD-iOS#165]
## 🛠 Issue

메인뷰 리팩토링

## 📝 To-do

- [x] 배너 섹션 리팩토링
- [x] 배너 무한스크롤 구현
- [x] 배너 타이머 구현
