### ISSUE TITLE
[FIX] 코스, 일정 등록 QA

### ISSUE THREAD

**Issue by ParkSY0919** [TeamDATEROAD/DATEROAD-iOS#175]
## 🛠 Issue

- 코스 등록하기 QA
- 일정 등록하기 QA

## 📝 To-do

- [x] `지난일정 코스 등록` & `일정 불러와 일정 등록` 시 불러온 데이터에 해당된 태그 값 더블 클릭해야 선택 취소됨
- [x] `지난일정 코스 등록`중 `데이트 일자`의 형식이 서버 통신 형식과 달라 발생하는 오류 픽스
- [ ] 코스 등록하기 레이아웃 조정
- [x] 지난일정 코스 등록시 서버 통신 에러 발생하여도 에러뷰 안뜸
