### ISSUE TITLE
[FIX] 프로필 온보딩 자체 QA

### ISSUE THREAD

**Issue by seuriseuljjeok** [TeamDATEROAD/DATEROAD-iOS#181]
## 🛠 Issue

프로필 온보딩 자체 QA

## 📝 To-do

- [x] 온보딩 이미지 2 깨짐
- [ ] 프로필 등록 닉네임 & 태그 분기 처리 이슈
- [x] 프로필 등록 기본 이미지 깨짐
- [ ] 5자 이상 입력 시 잘못된 에러 메세지 출력
- [ ] 닉네임 텍스프 필드 외부 영역 탭하면 닉네임 에러 처리 초기화됨
- [x] 닉네임 특수문자 제외
