### ISSUE TITLE
[FIX] 코스 상세 QA 반영

### ISSUE THREAD

**Issue by kms0233** [TeamDATEROAD/DATEROAD-iOS#191]
## 🛠 Issue

QA 바탕으로 수정할 예정입니다
## 📝 To-do

- [x] 스크롤 시 헤더 부분 글씨 비침
- [x] 코스 타임라인 숫자 오류 (2부터 시작)
- [x] 코스 상세에서 아래로 드래그 할 때 그라디언트는 드래그 되지 않음
