### ISSUE TITLE
[FIX] 1차 iOS QA 적용

### ISSUE THREAD

**Issue by seuriseuljjeok** [TeamDATEROAD/DATEROAD-iOS#195]
## 🛠 Issue

1차 iOS QA 적용

## 📝 To-do

- [x] 마이페이지 메인 → 포인트 시스템 소개 버튼이 ‘포인트 제도 소개’로 워딩 변경
- [x] 홈화면 스크롤 여러번 또는 왔다갔다 할 때 버벅거리면서 배경 보라색으로 변경됨
- [x] 메인 HOT & NEW 코스 카드 이미지 정사각형으로 변경
