### ISSUE TITLE
[FIX] 로딩뷰 & 에러뷰 변경사항 적용

### ISSUE THREAD

**Issue by seuriseuljjeok** [TeamDATEROAD/DATEROAD-iOS#202]
## 🛠 Issue

 로딩뷰 & 에러뷰 변경사항 적용

## 📝 To-do

- [ ] 로딩뷰 로티 적용
- [ ] 로딩뷰 로직 수정
- [ ] 에러뷰 변경된 이미지 적용
