### ISSUE TITLE
[FEAT] 엠플리튜드 초기 세팅 & 메인 적용

### ISSUE THREAD

**Issue by seuriseuljjeok** [TeamDATEROAD/DATEROAD-iOS#206]
## 🛠 Issue

엠플리튜드 초기 세팅 & 일부 적용

## 📝 To-do

- [x] 엠플리튜드 초기 세팅
- [x] 유저 정보 세팅 
- [x] 유저 정보 리셋
- [x] 홈 적용
