### ISSUE TITLE
[FEAT] Amplitude 나머지 적용

### ISSUE THREAD

**Issue by seuriseuljjeok** [TeamDATEROAD/DATEROAD-iOS#214]
## 🛠 Issue

Amplitude 나머지 적용

## 📝 To-do

- [x] 홈 화면 진입 시 코스 리스트 id
- [x] 홈 화면 진입 시 코스 리스트 이름
- [x] 홈 화면 진입 시 코스 리스트 지역 필터
- [x] 홈 화면 진입 시 코스 리스트 비용 필터
- [x] 홈 화면 진입 시 유저 이름, 유저 포인트 삭제 (user property와 중복됨)
- [x] 유저의 총 코스 구매 횟수 user property 
- [x] 유저가 등록한 코스 횟수 user property 
- [x] 유저의 다가오는 데이트 일정 개수 user property
