### ISSUE TITLE
[FEAT] 코스 상세 Amplitude 적용

### ISSUE THREAD

**Issue by kms0233** [TeamDATEROAD/DATEROAD-iOS#216]
## 🛠 Issue

코스 상세 관련된 Amplitude 적용 예정입니다!!

## 📝 To-do

- [x] 코스 리스트 아이디
- [x] 코스 리스트 이름
- [x] 포인트로 코스 열람하기 버튼 여부
- [x] 확인 버튼 클릭 여부
- [x] 코스 리스트 좋아요 여부
- [x] User Property -> 유저의 무료 열람 횟수
