### ISSUE TITLE
[FEAT] 데이트일정 및 열람한 코스 Amplitude 적용

### ISSUE THREAD

**Issue by cirtuare** [TeamDATEROAD/DATEROAD-iOS#218]
## 🛠 Issue
데이트일정 Amplitude를 적용합니다

## 📝 To-do

- 데이트일정
- [x] 데이트일정 뷰 진입
- [x] 다가올 데이트 일정 개수
- [x] 일정 추가 버튼 클릭
- 데이트일정 상세
- [x] 데이트일정 상세 뷰 진입 (유입 경로)
- [x] 카카오톡 공유 버튼 클릭 (데이트 코스 개수, 총 데이트 소요 시간)
- [x] 카카오톡 공유 버튼 - 취소 클릭 (데이트 코스 개수, 총 데이트 소요 시간)
- [x] 카카오톡 공유 버튼 - 열기 클릭 (데이트 코스 개수, 총 데이트 소요 시간)
- 내가 열람한 코스
- [x] 내가 열람한 코스 진입
- [x] 내가 열람한 코스 뒤로가기 버튼 클릭
