### ISSUE TITLE
[FIX] 2차 QA 전 디테일 수정

### ISSUE THREAD

**Issue by seuriseuljjeok** [TeamDATEROAD/DATEROAD-iOS#224]
## 🛠 Issue

 2차 QA 전 디테일 수정

## 📝 To-do

- [x] 로그인 중간에 취소할 경우 스플래시로 보내기
- [x] 로딩뷰 시간 조정
- [x] 프로필 편집 로딩뷰 추가
