### ISSUE TITLE
[FIX] iOS 2차 QA 적용

### ISSUE THREAD

**Issue by seuriseuljjeok** [TeamDATEROAD/DATEROAD-iOS#228]
## 🛠 Issue

iOS 2차 QA 적용

## 📝 To-do

- [x] 메인 유저 프로필 외부 검정색 배경 제거
- [x] 메인 Hot 코스 스크롤 걸리지 않도록 수정
- [x] 나머지 로딩뷰 로직 리팩
- [x] 나머지 에러뷰 로직 리팩
