### ISSUE TITLE
[FEAT] App Icon 및 Display Name 추가

### ISSUE THREAD

**Issue by seuriseuljjeok** [TeamDATEROAD/DATEROAD-iOS#236]
## 🛠 Issue

App Icon 및 Display Name 추가

## 📝 To-do

- [x] App Icon 추가
- [x] Display Name 추가
- [x] base url 변경
- [x] 메인에서 서버 에러 발생 시 user defaults 날리고 로그인으로 이동
