### ISSUE TITLE
[HOTFIX] 1.0.0 버전 수정사항 적용

### ISSUE THREAD

**Issue by seuriseuljjeok** [TeamDATEROAD/DATEROAD-iOS#243]
## 🛠 Issue

1.0.0 버전 수정사항 적용

## 📝 To-do

- [x] 프로필 관련 로직 수정
- [x] 탈퇴 시 로딩뷰 시점 수정
- [x] 배너 인덱스 버벅임 수정
- [x] 메인 프로필 클립 수정
- [x] 코스 둘러보기 메모리 최적화
