### ISSUE TITLE
[UPDATE] 1.0.1 버전 업데이트

### ISSUE THREAD

**Issue by seuriseuljjeok** [TeamDATEROAD/DATEROAD-iOS#250]
## 🛠 Issue

1.0.0 버전 보완 및 업데이트

## 📝 To-do

- [x] 메인 이미지 로딩 속도 조정
- [x] 메인 프로필 이미지 배경색 설정
- [x] 메인 뷰 로딩 리팩
