### ISSUE TITLE
[REFACTOR] 데이터 로딩 리팩토링

### ISSUE THREAD

**Issue by seuriseuljjeok** [TeamDATEROAD/DATEROAD-iOS#264]
## 🛠 Issue

스켈레톤을 사용하는 뷰에 투명 로딩뷰를 함께 띄우는 걸로 리펙

## 📝 To-do

- [x] 투명 로티 추가
- [x] 마이페이지 투명 로티 적용
- [x] 스켈레톤을 사용하는 뷰에 투명 로딩뷰를 함께 띄우기
- [x] 다가오는 데이트 일정 로딩뷰 레이아웃 수정
