### ISSUE TITLE
[Fix] QA 적용 및 데이터 로딩 방식 변경

### ISSUE THREAD

**Issue by ParkSY0919** [TeamDATEROAD/DATEROAD-iOS#266]
## 🛠 Issue

- QA 및 데이터 로딩 방식을 변경합니다.

## 📝 To-do

- [ ] '코스 상세보기' 좋아요 로직 수정
- [x] 바텀 시트 동작 시 blurView 페이드인 효과 적용
- [x] '코스&일정 등록 2' `장소명` 공백 제한
- [x] '코스&일정 등록 2' `cell 장소명` 레이아웃 버그 수정
- [x] '코스&일정 등록 2' 장소 폰트 미적용 수정
- [x] 데이터 로딩 방식 변경
  - 참고: https://github.com/TeamDATEROAD/DATEROAD-iOS/pull/265
