### ISSUE TITLE
[HOTFIX] 이슈 해결

### ISSUE THREAD

**Issue by seuriseuljjeok** [TeamDATEROAD/DATEROAD-iOS#268]
## 🛠 Issue

배포 후 자체 QA 이슈 해결

## 📝 To-do

- [x] '코스 상세' 좋아요 개수 이슈 해결
- [x] 코스 둘러보기 이미지 로딩 깜빡임 이슈 해결
- [x] 다가오는 데이트 일정 카드 내 성향 태그 이슈 해결
- [x] 일정 및 코스 등록 후 로딩 배경 투명으로 변경
- [x] 폰트 지원 이슈 해결
