### ISSUE TITLE
[HOTFIX] Troubleshooting various issues

### ISSUE THREAD

**Issue by ParkSY0919** [TeamDATEROAD/DATEROAD-iOS#269]
## 🛠 Issue

- '등록, 코스 둘러보기' 수정사항 반영
## 📝 To-do

- `코스 등록`
  - [x] 뷰 3 `content TextView`의 `enter 키` 입력시 키보드 내려가는 기능 비활성화 (뒷 배경 터치로 닫기)
  - [x] 뷰 3 키보드 `완료` 버튼 추가
  - [x] 뷰 3 `content TextView` 입력 중 글자 사라짐 현상 수정 
      (폰트 지원 이슈라서 SystemFont로 대응)

- `코스 둘러보기`
  - [x] 필터링 버튼 누르면 CollectionView 최상단 이동 기능 추가

- `코스 상세보기`
  - [x] 게시글 Title, 데이트 장소 이름 trailing 미설정 수정

## 🔥 폰트 지원 이슈 대응 목록
- [x] 코스&일정 등록 1, 2, 3
- [x] 메인 [탭바]
  - [x] `새로 올라왔어요` dateTitleLabel 레이아웃 버그 대응
- [x] 코스 둘러보기 [탭바]
- [x] 코스 상세보기
  - [x] `title`, `timeLine` 레이아웃 버그 대응
- [x] 데이트 일정
- [x] 데이트 일정 상세보기
  - [x] `cell` 중 `placeLabel` 레이아웃 버그 대응
- [x] 지난 데이트
- [x] 지난 데이트 상세보기
  - [x] `cell` 중 `placeLabel` 레이아웃 버그 대응
- [x] 열람한 코스 [탭바]
- [x] 내가 열람한 코스 (NavViewed)
- [x] 마이페이지
- [x] 마이페이지 [등록, 수정]
- [x] 포인트 내역
- [x] 내가 등록한 코스
