### ISSUE TITLE
[HOTFIX] 프로필(등록, 변경), 열람한코스(탭바) 수정

### ISSUE THREAD

**Issue by ParkSY0919** [TeamDATEROAD/DATEROAD-iOS#272]
## 🛠 Issue

- 프로필(등록, 변경) 중 사진 등록 기능 정상화
- 열람한코스(탭바) 로직 수정

## 📝 To-do

- [x] 프로필(등록) 사진 관련 기능 정상화
- [x] 프로필(변경) 사진 관련 기능 정상화
- [x] 열람한코스(탭바) guard let 관련 수정
