### ISSUE TITLE
[FIX] 코스 상세 SE 분기 처리를 통한 레이아웃 설정

### ISSUE THREAD

**Issue by kms0233** [TeamDATEROAD/DATEROAD-iOS#34]
## 🛠 Issue

코스 상세 SE 기기 대응 이슈로 SE만 따로 분기처리를 통해 다르게 UI를 만들 예정인데.. 할 수 있을지 모르겠어요

## 📝 To-do

- [ ] MainContents에서 본문만 Cell 분리하기
- [ ] SE의 너비를 이용한 분기 처리 
- [ ] 지역 필터링 바텀 시트 구현
