### ISSUE TITLE
[FEAT] 코스 등록하기 2 UI 및 기능 구현

### ISSUE THREAD

**Issue by ParkSY0919** [TeamDATEROAD/DATEROAD-iOS#35]
## 🛠 Issue

- 코스 등록하기 2 UI 및 기능 구현

## 📝 To-do

- [x] 상단 이미지 CollectionView [코스 등록하기 1] 파트 재활용하기
- [x] TextField 영역 UI 구현
- [x] 장소등록 영역 CollectionView 구현
- [x] TextField 기능 구현 (picker 등)
- [x] 장소등록 드래그 앤 드롭 구현
- [x] 각 파트 유효성 검사 진행 후 다음 버튼 활성화
