### ISSUE TITLE
[REFACTOR] 코스 등록하기 뷰 공용 컴포넌트 적용 및 리펙토링

### ISSUE THREAD

**Issue by ParkSY0919** [TeamDATEROAD/DATEROAD-iOS#48]
## 🛠 Issue

- TagButton 컬렉션뷰로 구현함과 더불어 바텀시트 뷰 구현한 것 공용 컴포넌트로 리펙토링 하고자 합니다.
- `코스 등록하기 2` 중 '소용 시간' 터치시 나타나는 `CustomPickerView` 기기대응
- `코스 등록하기 2` 중 cell을 전부 삭제했을 때에 '완료' 텍스트에서 편집으로 바뀌나, 다음 셀을 등록했을 때 해당 cell이 editMode의 이미지로 되고 있는 상황. 이를 해결해야함
- '코스 등록하기 3'에서 발생한 이슈 해결

## 📝 To-do

- [x] cell 삭제 버튼 구현
- [x] ImagePicker 구현
- [x] TagButton 컬렉션뷰로 전환
- [x] datepicker 2개와 '소요 시간' 구현하던 바텀 시트 공용컴포넌트로 전환
- [x] 코스 등록하기 1 방문일자 "yyyy.mm.dd" 형식으로 변경하기
- [x] CustomPicker 바텀 inset 조정
- [x] editMode 로직 수정
- [x] 키보드 대응
- [x] alert 적용
- [x] '코스 등록하기 1' 중 '다음' 버튼 활성화 로직 재정리
