### ISSUE TITLE
[Feat] 코스 상세 UI & 분기 처리 구현

### ISSUE THREAD

**Issue by kms0233** [TeamDATEROAD/DATEROAD-iOS#53]
## 🛠 Issue

드디어 코스 상세 디자인이 확정되어서 열람 전 뷰 작업 들어갑니당!!
디테일 필요한 부분들 수정한 뒤 간단한 로직 구현 예정입니다!! 
## 📝 To-do

- [x] 열람 전 뷰 UI 구현
- [ ] 삭제 바텀 시트 구현
- [ ] ViewModel로 로직 처리하기
- [ ] 네비게이션바 추가
