### ISSUE TITLE
[FEAT] 코스 등록하기 3 UI 및 기능 구현

### ISSUE THREAD

**Issue by ParkSY0919** [TeamDATEROAD/DATEROAD-iOS#56]
## 🛠 Issue

- 코스 등록하기 3 UI 및 기능 구현

## 📝 To-do

- [x] 전체 뷰 스크롤 구현
- [x] 상단 이미지 CollectionView [코스 등록하기 1] 파트 재활용하기
- [x] Course 본문 영역 구현
- [x] Course 총 비용 영역 구현
- [x] 각 파트 유효성 검사 진행 후 `완료` 버튼 활성화
