### ISSUE TITLE
[FEAT] 엠티뷰 적용

### ISSUE THREAD

**Issue by cirtuare** [TeamDATEROAD/DATEROAD-iOS#64]
## 🛠 Issue
- 뷰들에 엠티뷰를 적용합니다.

## 📝 To-do

- [x] 내가 등록한 코스 엠티뷰 적용
- [x] 내가 열람한 코스 엠티뷰 적용
- [ ] 포인트 내역 엠티뷰 적용
