### ISSUE TITLE
[FIX] GUI 수정 사항 반영 & 버튼 에러 해결 

### ISSUE THREAD

**Issue by kms0233** [TeamDATEROAD/DATEROAD-iOS#69]
## 🛠 Issue

버튼 GUI 수정하고 필터링 버튼 에러 수정할 계획입니닷

## 📝 To-do

- [x] GUI 변경사항 반영
- [x] 필터링 버튼 에러 해결
- [x] Model 구조 확인하기
